// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYK0EwQwYttzXxCVSvKFGUBfEnwGt4Xs',
    appId: '1:67115458375:web:5cb25b772321839aab7662',
    messagingSenderId: '67115458375',
    projectId: 'gemhub-mobile-app',
    authDomain: 'gemhub-mobile-app.firebaseapp.com',
    storageBucket: 'gemhub-mobile-app.firebasestorage.app',
    measurementId: 'G-5PP548D9FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdbAzTi4Q7iCizG9cqew26H6hjquPOcBc',
    appId: '1:67115458375:android:1c8505642920ba1eab7662',
    messagingSenderId: '67115458375',
    projectId: 'gemhub-mobile-app',
    storageBucket: 'gemhub-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflUBocCPXg9oM1-AycyvLe9FQ0DON-mQ',
    appId: '1:67115458375:ios:358ca74d5c86f567ab7662',
    messagingSenderId: '67115458375',
    projectId: 'gemhub-mobile-app',
    storageBucket: 'gemhub-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.gemhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCflUBocCPXg9oM1-AycyvLe9FQ0DON-mQ',
    appId: '1:67115458375:ios:358ca74d5c86f567ab7662',
    messagingSenderId: '67115458375',
    projectId: 'gemhub-mobile-app',
    storageBucket: 'gemhub-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.gemhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCYK0EwQwYttzXxCVSvKFGUBfEnwGt4Xs',
    appId: '1:67115458375:web:fb1f80b511275e5eab7662',
    messagingSenderId: '67115458375',
    projectId: 'gemhub-mobile-app',
    authDomain: 'gemhub-mobile-app.firebaseapp.com',
    storageBucket: 'gemhub-mobile-app.firebasestorage.app',
    measurementId: 'G-JB8YWQGX0C',
  );
}
